模糊综合评价模型

In [ ]:
import numpy as np

#1、一级模糊综合评判
#影响运行费用的各因素的单因素评价矩阵为：
R23 = np.array([
       [0.18,0.14,0.18,0.14,0.13,0.23],
       [0.15,0.20,0.15,0.25,0.10,0.15],
       [0.25,0.12,0.13,0.12,0.18,0.20],
       [0.16,0.15,0.21,0.11,0.20,0.17],
       [0.23,0.18,0.17,0.16,0.15,0.11],
       [0.19,0.13,0.12,0.12,0.11,0.33],
       [0.17,0.16,0.15,0.08,0.25,0.19]])
#权重分配为：
A23 = np.array([0.20,0.15,0.10,0.10,0.20,0.15,0.10])
#评价结果
#np.dot()是用于记算两个数组的点积，对于一维数组它计算的是两个数组的内积
#对于二维数组（矩阵），计算的是矩阵乘法
B23 = np.dot(A23,R23)
B23

array([0.191 , 0.1565, 0.1595, 0.1465, 0.1505, 0.196 ])

In [10]:
# 2、二级模糊综合评判
# 产品情况的二级评判如下：
R1 = np.array([
    [0.12, 0.18, 0.17, 0.23, 0.13, 0.17],
    [0.15, 0.13, 0.18, 0.25, 0.12, 0.17],
    [0.14, 0.13, 0.16, 0.18, 0.20, 0.19],
    [0.12, 0.14, 0.15, 0.17, 0.19, 0.23],
    [0.16, 0.12, 0.13, 0.25, 0.18, 0.16]])
A1 = np.array([0.15, 0.40, 0.25, 0.10, 0.10])
B1 = np.dot(A1,R1)
B1

array([0.141 , 0.1375, 0.1655, 0.2215, 0.1545, 0.18  ])

In [12]:
#销售能力二级评判如下：
R2 = np.array([
    [0.13, 0.15, 0.14, 0.18, 0.16, 0.25],
    [0.12, 0.16, 0.13, 0.17, 0.19, 0.23],
    B23,                                     #数组可以直接放在矩阵里面
    [0.14, 0.13, 0.15, 0.16, 0.18, 0.24],
    [0.16, 0.15, 0.15, 0.17, 0.18, 0.19]])
A2 = np.array([0.2, 0.15, 0.25, 0.25, 0.15])
B2 = np.dot(A2,R2)
B2

array([0.15075 , 0.148125, 0.147375, 0.163625, 0.170125, 0.222   ])

In [13]:
#市场欲求二级评判
R3 = np.array([
    [0.15, 0.14, 0.13, 0.18, 0.14, 0.26],
    [0.16, 0.15, 0.18, 0.14, 0.16, 0.21]])
A3 = np.array([0.55, 0.45])
B3 = np.dot(A3,R3)
B3

array([0.1545, 0.1445, 0.1525, 0.162 , 0.149 , 0.2375])

In [16]:
#3、三级模糊综合评判
R = np.array([B1,B2,B3])
A = np.array([0.4, 0.3 ,0.3])
B = np.dot(A,R)
B

array([0.147975 , 0.1427875, 0.1561625, 0.1862875, 0.1575375, 0.20985  ])