# 特征值与特征向量

In [2]:
import numpy as np
from numpy.linalg import eig

A = np.array([[0,-2,2],[-2,-3,4],[2,4,-3]])
values, vectors = eig(A)
print('A的特征值为:', values)
print('A的特征向量为:', vectors)

A的特征值为: [ 1. -8.  1.]
A的特征向量为: [[ 0.94280904 -0.33333333 -0.2981424 ]
 [-0.23570226 -0.66666667  0.74535599]
 [ 0.23570226  0.66666667  0.59628479]]


验证P^-1AP = ^(对角矩阵即特征值构成的对角矩阵)

In [5]:
import numpy as np
from numpy.linalg import eig, inv

A = np.array([[0,-2,2],[-2,-3,4],[2,4,-3]])
values, vectors = eig(A)
check = np.dot(inv(vectors), A).dot(vectors)
print(check)

[[ 1.00000000e+00 -2.98175964e-16 -1.24479536e-16]
 [-1.69319250e-17 -8.00000000e+00 -1.82035372e-16]
 [-3.11430858e-18  5.36264070e-16  1.00000000e+00]]
