# 向量和矩阵的运算

形状为(n,)的一维数组既可以看成行向量，又可以看成列向量，因此inner(a,b)与矩阵乘法dot(a,b)等价

In [7]:
from numpy import arange, cross, inner, dot
from numpy.linalg import norm

a = arange(1,4)
b = arange(4,7)  #创建数组
print('a的二范数为:', norm(a))
print('a点乘b=', dot(a,b))  #a.dot(b)
print('a,b的内积=', inner(a,b))
print('a叉乘b=', cross(a,b))

a的二范数为: 3.7416573867739413
a点乘b= 32
a,b的内积= 32
a叉乘b= [-3  6 -3]


In [18]:
import numpy as np
import numpy.linalg as la

A = np.arange(1,17).reshape(4,4)
B = np.eye(4)
print('A的行列式为:', la.det(A))
print('A的秩为:', la.matrix_rank(A))
print('A的转置矩阵为:', A.T)
print('所求的逆矩阵为:', la.inv(A+10*B))
print('A的平方为:', A.dot(A))
print('A,B的乘积为:', A.dot(B))
print('横连矩阵为:', np.c_[A, B])
print('纵连矩阵为:', np.r_[A, B])
print('提出A的左上角子块构成的矩阵为:', A[0:2,0:2])
A2 = A.copy(); A2 = np.delete(A2, 3, axis=0)  #删除第四行
print(A2)

A的行列式为: 0.0
A的秩为: 2
A的转置矩阵为: [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
所求的逆矩阵为: [[ 0.11277778  0.00333333 -0.00611111 -0.01555556]
 [-0.005       0.09       -0.015      -0.02      ]
 [-0.02277778 -0.02333333  0.07611111 -0.02444444]
 [-0.04055556 -0.03666667 -0.03277778  0.07111111]]
A的平方为: [[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]
A,B的乘积为: [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
横连矩阵为: [[ 1.  2.  3.  4.  1.  0.  0.  0.]
 [ 5.  6.  7.  8.  0.  1.  0.  0.]
 [ 9. 10. 11. 12.  0.  0.  1.  0.]
 [13. 14. 15. 16.  0.  0.  0.  1.]]
纵连矩阵为: [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
提出A的左上角子块构成的矩阵为: [[1 2]
 [5 6]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
