灰色关联评价

In [1]:
import numpy as np

#从用户输入中接受参评数目和指标数目，并将输入的字符串转换为数值
n = int(input('请输入参评数目：'))
m = int(input('请输入指标数目：'))
# print(n,m)
#接受用户输入的类型矩阵，该矩阵指示了每个指标的类型
print('请输入类型矩阵：1：极大型，2：极小型，3：中间型，4：区间型')
kind = input().split(' ')  #将输入的字符串按空格分割，形成列表

#接收用户输入的矩阵并转化为numpy数组
#A = [9,10,175,120;8,7,164,80;6,3,157,90]
print('请输入矩阵：')
A = np.zeros(shape=(n,m))  #初始化一个n行m列的全零矩阵A
for i in range(n):
    A[i] = input().split(" ")  #接收每行输入的数据
    A[i] = list(map(float,A[i]))  #将接收到的字符串列表转换为浮点数列表
print('输入矩阵为：\n{}'.format(A))

#极小型指标转换为极大型指标
def mintomax(x, maxx):
    x = list(x)  #将输入的指标转化为列表
    ans = [[(maxx-e)] for e in x]  #记算最大值与每个指标的差，并放入新列表中
    return np.array(ans)  #将列表转化为np数组并返回
#中间型指标转换为极大型指标
def midtomax(bestx, x):
    x = list(x)
    h = [abs(e-bestx) for e in x]  #记算每个值与最优值之间的绝对差
    M = max(h)  #找到最大的差值
    if M == 0:
        M = 1  #防止最大值为0
    ans = [[(1-e/M)] for e in h]  #记算每个差值占最大差值的比例，并从1中减去
    return np.array(ans)
#区间型指标转换为极大型指标
def regtomax(lowx, highx, x):
    x = list(x)
    M = max(lowx-min(x), max(x)-highx)  #记算指标值超出区间的最大距离
    if M == 0:
        M =1
    ans = []
    for i in range(len(x)):
        if x[i]<lowx:
            ans.append([(1-(lowx-x[i])/M)])
        elif x[i] > highx:
            ans.append([(1-(x[i]-highx)/M)])
        else:
            ans.append([1])
    return np.array(ans)

#统一指标类型
X = np.zeros(shape=(n,1))
for i in range(m):
    if kind[i] == '1':
        v = np.array(A[:,i])
    elif kind[i] == '2':
        maxA = max(A[:,i])
        v = mintomax(A[:,i], maxA)
    elif kind[i] == '3':
        print('类型三：请输入最优值：')
        bestA = eval(input())
        v = midtomax(bestA, A[:, i])
    elif kind[i] == '4':
        print('类型四：请输入区间[a,b]值a：')
        lowA = eval(input())
        print('类型四：请输入区间[a,b]值b：')
        highA = eval(input())
        v = regtomax(lowA, highA, A[:, i])
    if i == 0:
        X = v.reshape(-1,1)  #如果是第一个指标，直接替换X数组  reshape(-1,*)表示自动识别行数
    else:
        X = np.hstack([X, v.reshape(-1,1)])  #如果不是第一个指标，则将新指标拼接在X数组上
print('统一指标后矩阵为：\n{}'.format(X))

请输入类型矩阵：1：极大型，2：极小型，3：中间型，4：区间型
请输入矩阵：
输入矩阵为：
[[  9.  10. 175. 120.]
 [  8.   7. 164.  80.]
 [  6.   3. 157.  90.]]
类型三：请输入最优值：
类型四：请输入区间[a,b]值a：
类型四：请输入区间[a,b]值b：
统一指标后矩阵为：
[[9.  0.  0.  0. ]
 [8.  3.  0.9 0.5]
 [6.  7.  0.2 1. ]]


In [2]:
#数据预处理
Mean = np.mean(X,axis=0)
Z = X / Mean
print('预处理后的矩阵：')
print(Z)

预处理后的矩阵：
[[1.17391304 0.         0.         0.        ]
 [1.04347826 0.9        2.45454545 1.        ]
 [0.7826087  2.1        0.54545455 2.        ]]


In [3]:
#母序列
Y = np.max(Z,axis=1)  #母序列是虚拟的，用每一行的最大值构成的列向量表示母序列
X = Z

In [4]:
#记算得分
absX0_Xi = np.abs(X - Y.reshape(-1,1))
a = np.min(absX0_Xi)
b = np.max(absX0_Xi)
rho = 0.5
gramma = (a+rho*b)/(absX0_Xi + rho*b)  #记算子序列中各行指标与母序列的关联系数
W = np.mean(gramma,axis=0) / np.sum(np.mean(gramma))  #记算各个指标的均值的权重
score = np.sum(X * W,axis=1)
stand_s = score / np.sum(score)  #归一化
sorted_s = np.sort(stand_s)[::-1]  #[::-1] 表示将排序结果反转，得到降序排列。
index = np.argsort(stand_s)[::-1]  #排序后的索引
print('归一化后的得分以及对应的索引：')
print(sorted_s)
print(index)

归一化后的得分以及对应的索引：
[0.45160804 0.44937917 0.0990128 ]
[1 2 0]
