灰色关联分析

In [1]:
import numpy as np

#初始矩阵：[[55,24,10],[65,38,22],[75,40,18],[100,50,20]]
A = np.array(eval(input('请输入初始矩阵')))  #假设输入的形式是合法的python列表形式
#求出每一列的均值以供后续的数据预处理
Mean = np.mean(A, axis=0)
#预处理
A_norm = A / Mean
print('预处理后的矩阵为：')
print(A_norm)

预处理后的矩阵为：
[[0.74576271 0.63157895 0.57142857]
 [0.88135593 1.         1.25714286]
 [1.01694915 1.05263158 1.02857143]
 [1.3559322  1.31578947 1.14285714]]


In [2]:
#母序列
Y = A_norm[:,0]
print(Y)
#子序列
X = A_norm[:,1:]
absX0_Xi = np.abs(X - Y.reshape(-1,1))
a = np.min(absX0_Xi)   #全局中找到最小值
b = np.max(absX0_Xi)
rho = 0.5  #分辨系数
gamma = (a+rho*b)/(absX0_Xi + rho*b)
print('子序列中各个指标的灰色关联度分别为：')
print(np.mean(gamma,axis=0))

[0.74576271 0.88135593 1.01694915 1.3559322 ]
子序列中各个指标的灰色关联度分别为：
[0.76966578 0.60058464]
