线性整数/0-1规划

指派问题

In [15]:
from pulp import LpMaximize, LpMinimize, LpProblem, LpVariable, lpSum, value
import numpy as np

#创建最小化问题
problem = LpProblem(name='Assignment_Problem', sense=LpMinimize)
#定义目标函数系数（泳姿时间）
c = [66.8,75.6,87,58.6,57.2,66,66.4,53,78,67.8,84.6,59.4,70,74.2,69.6,57.2,67.4,71,83.8,62.4]
#定义决策变量（0-1变量）
x = [LpVariable(name=f'x{i+1}', cat='Binary') for i in range(20)]
#定义目标函数
problem += lpSum(c[i]*x[i] for i in range(20)), 'Total_Time'
#添加不等式约束
A = [
    [1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1]
    ]
b = np.ones(5)
for i in range(len(A)):
    problem += lpSum(A[i][j]*x[j] for j in range(20)) <= b[i], f'Person_Constraint_{i+1}'
#添加等式约束
Aeq = [
    [1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],
    [0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0],
    [0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0],
    [0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1]
    ]
beq = np.ones(4)
for i in range(len(Aeq)):
    problem += lpSum(Aeq[i][j] * x[j] for j in range(20)) == beq[i], f'Style_Constraint_{i+1}'
#求解问题
problem.solve()
#输出结果
print('分配结果为（0表示未选，1表示选中）：')
assignment = [int(value(x[i])) for i in range(20)]
assignment_matrix = np.array(assignment).reshape(5,4)
print(assignment_matrix)
print('最小时间为：')
print(value(problem.objective))

分配结果为（0表示未选，1表示选中）：
[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 0]]
最小时间为：
253.20000000000002
